-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 08, 2021 at 03:42 PM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 8.0.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cr12_mounteverest_gregor`
--
CREATE DATABASE IF NOT EXISTS `cr12_mounteverest_gregor` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `cr12_mounteverest_gregor`;

-- --------------------------------------------------------

--
-- Table structure for table `locations`
--

CREATE TABLE `locations` (
  `id` int(11) NOT NULL,
  `loc_name` varchar(30) NOT NULL,
  `price` float(6,2) NOT NULL,
  `descr_short` varchar(130) NOT NULL,
  `descr_long` mediumtext NOT NULL,
  `wiki_link` varchar(255) NOT NULL,
  `longitude` float(20,17) NOT NULL,
  `latitude` float(20,17) NOT NULL,
  `loc_image` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `locations`
--

INSERT INTO `locations` (`id`, `loc_name`, `price`, `descr_short`, `descr_long`, `wiki_link`, `longitude`, `latitude`, `loc_image`) VALUES
(1, 'Grand Canyon', 2365.35, 'The canyon and adjacent rim are contained within Grand Canyon National Park, the Kaibab National Forest, Grand Canyon–Parashant..', 'Nearly two billion years of Earth`s geological history have been exposed as the Colorado River and its tributaries cut their channels through layer after layer of rock while the Colorado Plateau was uplifted.[6] While some aspects about the history of incision of the canyon are debated by geologists,[7] several recent studies support the hypothesis that the Colorado River established its course through the area about 5 to 6 million years ago.[1][8][9] Since that time, the Colorado River has driven the down-cutting of the tributaries and retreat of the cliffs, simultaneously deepening.', 'https://en.wikipedia.org/wiki/Grand_Canyon', 36.41004943847656000, -113.68373870849610000, 'http://shallow.codes/images_CR12/loc01_grand_canyon.jpg'),
(2, 'Yosemite', 2779.75, 'Yosemite is one of the largest and least fragmented habitat blocks in the Sierra Nevada, and the park supports a diversity of..', 'The geology of the Yosemite area is characterized by granitic rocks and remnants of older rock. About 10 million years ago, the Sierra Nevada was uplifted and then tilted to form its relatively gentle western slopes and the more dramatic eastern slopes. The uplift increased the steepness of stream and river beds, resulting in the formation of deep, narrow canyons. About one million years ago, snow and ice accumulated, forming glaciers at the higher alpine meadows that moved down the river valleys. Ice thickness in Yosemite Valley may have reached 4,000 feet (1,200 m) during the early.', 'https://en.wikipedia.org/wiki/Yosemite_National_Park', 37.87357330322265600, -119.54840087890625000, 'http://shallow.codes/images_CR12/loc02_yosemite.jpg'),
(3, 'Yellowstone', 2595.95, 'Although Native Americans have lived in the Yellowstone region for at least 11,000 years,[11] aside from visits by mountain men..', 'Yellowstone National Park spans an area of 3,468.4 sq mi (8,983 km2),[3] comprising lakes, canyons, rivers, and mountain ranges.[10] Yellowstone Lake is one of the largest high-elevation lakes in North America and is centered over the Yellowstone Caldera, the largest supervolcano on the continent. The caldera is considered a dormant volcano. It has erupted with tremendous force several times in the last two million years.[13] Well over half of the world`s geysers[14][15] and hydrothermal features[16] are in Yellowstone, fueled by this ongoing volcanism. Lava flows and rocks from.', 'https://en.wikipedia.org/wiki/Yellowstone_National_Park', 44.47091674804687500, -110.60502624511719000, 'http://shallow.codes/images_CR12/loc03_yellowstone.jpg'),
(4, 'Maui', 2191.65, 'Maui`s diverse landscapes are the result of a unique combination of geology, topography, and climate. Each volcanic cone in the..', 'The older, western volcano has been eroded considerably and is cut by numerous drainages, forming the peaks of the West Maui Mountains (in Hawaiian, Mauna Kahalawai). Puʻu Kukui is the highest of the peaks at 5,788 feet (1,764 m). The larger, younger volcano to the east, Haleakalā, rises to more than 10,000 feet (3,000 m) above sea level, and measures 5 miles (8.0 km) from seafloor to summit. The eastern flanks of both volcanoes are cut by deeply incised valleys and steep-sided ravines that run downslope to the rocky, windswept shoreline. The valley-like Isthmus of Maui that separates.', 'https://en.wikipedia.org/wiki/Maui', 20.82148933410644500, -156.32948303222656000, 'http://shallow.codes/images_CR12/loc04_maui.jpg'),
(5, 'Glacier National Park', 2733.75, 'The region that became Glacier National Park was first inhabited by Native Americans. Upon the arrival of European explorers, it..', 'Glacier National Park`s mountains began forming 170 million years ago when ancient rocks were forced eastward up and over much younger rock strata. Known as the Lewis Overthrust, these sedimentary rocks are considered to have some of the finest examples of early life fossils on Earth. The current shapes of the Lewis and Livingston mountain ranges and positioning and size of the lakes show the telltale evidence of massive glacial action, which carved U-shaped valleys and left behind moraines that impounded water, creating lakes. Of the estimated 150 glaciers which existed in the park.', 'https://en.wikipedia.org/wiki/Glacier_National_Park_(U.S.)', 48.76582717895508000, -113.79782104492188000, 'http://shallow.codes/images_CR12/loc05_glacier_national_park.jpg'),
(6, 'New York City', 2867.75, 'Situated on one of the world`s largest natural harbors, New York City is composed of five boroughs, each of which is a county..', 'New York City traces its origins to a trading post founded on the southern tip of Manhattan Island by Dutch colonists in 1624. The settlement was named New Amsterdam (Dutch: Nieuw Amsterdam) in 1626 and was chartered as a city in 1653.[26] The city came under English control in 1664 and was renamed New York after King Charles II of England granted the lands to his brother, the Duke of York.[26][27] The city was regained by the Dutch in July 1673 and was renamed New Orange for one year and three months; the city has been continuously named New York since November 1674.[28][29] New York.', 'https://en.wikipedia.org/wiki/New_York_City', 40.78516769409180000, -73.97065734863281000, 'http://shallow.codes/images_CR12/loc06_new_york_city.jpg'),
(7, 'San Francisco', 2597.65, 'In 2019, San Francisco was the county with the seventh-highest income in the United States, with a per capita income of $139,405..', 'San Francisco was founded on June 29, 1776, when colonists from Spain established the Presidio of San Francisco at the Golden Gate and Mission San Francisco de Asís a few miles away, both named for Francis of Assisi.[3] The California Gold Rush of 1849 brought rapid growth, making it the largest city on the West Coast at the time. San Francisco became a consolidated city-county in 1856.[28] San Francisco`s status as the West Coast`s largest city peaked between 1870 and 1900, when around 25% of California`s population resided in the city proper.[29] After three-quarters of the city.', 'https://en.wikipedia.org/wiki/San_Francisco', 37.77791976928711000, -122.41331481933594000, 'http://shallow.codes/images_CR12/loc07_san_francisco.jpg'),
(8, 'New Orleans', 1873.50, 'New Orleans is world-renowned for its distinct music, Creole cuisine, unique dialects, and its annual celebrations and festivals.', 'Founded in 1718 by French colonists, New Orleans was once the territorial capital of French Louisiana before being traded to the United States in the Louisiana Purchase of 1803. New Orleans in 1840 was the third-most populous city in the United States,[16] and it was the largest city in the American South from the Antebellum era until after World War II. The city has historically been very vulnerable to flooding, due to its high rainfall, low lying elevation, poor natural drainage, and proximity to multiple bodies of water. State and federal authorities have installed a complex system.', 'https://en.wikipedia.org/wiki/New_Orleans', 29.98666572570800800, -90.11406707763672000, 'http://shallow.codes/images_CR12/loc08_new_orleans.jpg'),
(9, 'Honolulu - Oahu', 1978.00, 'Honolulu means \"sheltered harbor\"[9] or \"calm port\" in Hawaiian;[10] its old name, Kou, roughly encompasses the area from Nuʻuan..', 'As Hawaii is the only state with no incorporated places below the county level,[13] the U.S. Census Bureau recognizes the approximate area commonly referred to as the \"City of Honolulu\"—not to be confused with the \"City and County\"—as a census county division (CCD).[14] As of 2019, the estimated population of the Honolulu CCD was 390,738,[15] while that of the Honolulu census-designated place (CDP) was 345,064;[4] this corresponds to roughly a third of Hawaii`s 1.4 million residents. Honolulu is the most populated Oceanian city outside Australasia and ranks second to Auckland, New.', 'https://en.wikipedia.org/wiki/Honolulu', 21.34469985961914000, -157.86814880371094000, 'http://shallow.codes/images_CR12/loc09_honolulu_oahu.jpg'),
(10, 'Zion National Park', 1688.50, 'Zion National Park is an American national park located in southwestern Utah near the town of Springdale. A prominent feature of..', 'Human habitation of the area started about 8,000 years ago with small family groups of Native Americans, one of which was the semi-nomadic Basketmaker Anasazi (c. 300 CE). Subsequently, the Virgin Anasazi culture (c. 500) and the Parowan Fremont group developed as the Basketmakers settled in permanent communities.[4] Both groups moved away by 1300 and were replaced by the Parrusits and several other Southern Paiute subtribes. Mormons came into the area in 1858 and settled there in the early 1860s. In 1909, President William Howard Taft named the area Mukuntuweap National Monument.', 'https://en.wikipedia.org/wiki/Zion_National_Park', 37.28972625732422000, -113.02619171142578000, 'http://shallow.codes/images_CR12/loc10_zion_national_park.jpg'),
(11, 'Mount Rushmore Memorial', 1335.80, 'Mount Rushmore National Memorial is centered on a colossal sculpture carved into the granite face of Mount Rushmore (Lakota Thun..', 'South Dakota historian Doane Robinson is credited with conceiving the idea of carving the likenesses of noted figures into the mountains of the Black Hills of South Dakota in order to promote tourism in the region. His initial idea was to sculpt the Needles; however, Gutzon Borglum rejected the Needles because of the poor quality of the granite and strong opposition from the Lakota (Sioux), who consider the Black Hills to be sacred ground; it was originally included in the Great Sioux Reservation. The United States broke up the territory after gold was discovered in the Black Hills.', 'https://en.wikipedia.org/wiki/Mount_Rushmore', 43.87971878051758000, -103.45883178710938000, 'http://shallow.codes/images_CR12/loc11_mount_rushmore.jpg'),
(12, 'Grand Teton National Park', 1940.40, 'The human history of the Grand Teton region dates back at least 11,000  years, when the first nomadic hunter-gatherer Paleo-Ind..', 'Efforts to preserve the region as a national park began in the late 19th century, and in 1929 Grand Teton National Park was established, protecting the Teton Range`s major peaks. The valley of Jackson Hole remained in private ownership until the 1930s, when conservationists led by John D. Rockefeller Jr. began purchasing land in Jackson Hole to be added to the existing national park. Against public opinion and with repeated Congressional efforts to repeal the measures, much of Jackson Hole was set aside for protection as Jackson Hole National Monument in 1943. The monument was abolished.', 'https://en.wikipedia.org/wiki/Grand_Teton_National_Park', 43.79571914672851600, -110.64099884033203000, 'http://shallow.codes/images_CR12/loc12_grand_teton_national_park.jpg'),
(13, 'Washington D.C.', 1538.79, 'The U.S. Constitution provided for a federal district under the exclusive jurisdiction of U.S. Congress; the district is there..', 'The city is divided into quadrants centered on the Capitol Building, and there are as many as 131 neighborhoods. According to the 2020 Census,[14] it has a population of 689,545, which makes it the 20th-most populous city in the U.S. and gives it a population larger than that of two U.S. states: Wyoming and Vermont.[15] Commuters from the surrounding Maryland and Virginia suburbs raise the city`s daytime population to more than one million during the workweek.[16] Washington`s metropolitan area, the country`s sixth-largest (including parts of Maryland, Virginia and West Virginia).', 'https://en.wikipedia.org/wiki/Washington,_D.C', 38.94886779785156000, -77.05302429199219000, 'http://shallow.codes/images_CR12/loc13_washington_DC.jpg'),
(14, 'Moab', 1762.85, 'The Biblical name Moab refers to an area of land located on the eastern side of the Jordan River. Some historians believe the..', 'During the period between 1829 and the early 1850s, the area around what is now Moab served as the Colorado River crossing along the Old Spanish Trail. Latter-day Saint settlers attempted to establish a trading fort at the river crossing called the Elk Mountain Mission in April 1855 to trade with travellers attempting to cross the river. Forty men were called on this mission. There were repeated Indian attacks, including one on September 23, 1855, in which James Hunt, companion to Peter Stubbs, was shot and killed by a Native American.[12][13] After this last attack, the fort was.[14]', 'https://en.wikipedia.org/wiki/Moab,_Utah', 38.59663009643555000, -109.55091857910156000, 'http://shallow.codes/images_CR12/loc14_moab.jpg'),
(15, 'Lake Tahoe', 2749.20, 'The lake was formed about two million years ago as part of the Lake Tahoe Basin, and its modern extent was shaped during the ice..', 'Lake Tahoe is the second deepest lake in the U.S., with a maximum depth of 1,645 feet (501 m),[1][9] trailing Oregon`s Crater Lake at 1,949 ft (594 m).[9] Tahoe is the 16th[10] deepest lake in the world, and the fifth deepest in average depth. It is about 22 mi (35 km) long and 12 mi (19 km) wide and has 72 mi (116 km) of shoreline and a surface area of 191 square miles (490 km2). The lake is so large that its surface is noticeably convex due to the curvature of the earth. At lake level the opposing shorelines are below the horizon at its widest parts; by nearly 100 feet (30 m) at its.', 'https://en.wikipedia.org/wiki/Lake_Tahoe', 39.10816955566406000, -120.02849578857422000, 'http://shallow.codes/images_CR12/loc15_lake_tahoe.jpg'),
(16, 'Bar Harbor', 2507.70, 'Bar Harbor is a town on Mount Desert Island in Hancock County, Maine, United States. As of the 2010 census, its population is 5..', 'The town of Bar Harbor was founded on the northeast shore of Mount Desert Island, which the Wabanaki Indians knew as Pemetic, meaning \"range of mountains\" or \"mountains seen at a distance.\" The Wabanaki seasonally fish, hunt and gather berries, clams, and other shellfish in the area. They speak of Bar Harbor as Man-es-ayd`ik (\"clam-gathering place\") or Ah-bays`auk (\"clambake place\"), leave great piles of shells as evidence of this abundance. In early September 1604, French explorer Samuel de Champlain ran aground on a rock ledge believed to be Egg Rock, just off Otter Cliffs, and when.', 'https://en.wikipedia.org/wiki/Bar_Harbor,_Maine', 44.38659667968750000, -68.19883728027344000, 'http://shallow.codes/images_CR12/loc16_bar_harbor.jpg'),
(17, 'Kauai', 2850.55, 'In 1778, Captain James Cook arrived at Waimea Bay, the first European known to have reached the Hawaiian islands. He named the..', 'During the reign of King Kamehameha, the islands of Kauaʻi and Niʻihau were the last Hawaiian Islands to join his Kingdom of Hawaiʻi. Their ruler, Kaumualiʻi, resisted Kamehameha for years. King Kamehameha twice prepared a huge armada of ships and canoes to take the islands by force, and twice failed; once due to a storm, and once due to an epidemic. In the face of the threat of a further invasion, however, Kaumualiʻi decided to join the kingdom without bloodshed, and became Kamehameha`s vassal in 1810. He ceded the island to the Kingdom of Hawaiʻi upon his death in 1824. In 1815, a.', 'https://en.wikipedia.org/wiki/Kauai', 22.11222457885742200, -159.52778625488280000, 'http://shallow.codes/images_CR12/loc17_kauai.jpg'),
(18, 'San Diego', 1844.85, 'Historically home to the Kumeyaay people, San Diego is frequently referred to as the \"Birthplace of California\", as it was the..', 'San Diego`s main economic engines are military and defense-related activities, tourism, international trade, research, and manufacturing. The city is the economic center of the San Diego–Tijuana conurbation, the second most populous transborder metropolitan area in the western hemisphere (after Detroit–Windsor), home to an estimated 4,922,723 people as of 2012.[13] The primary border crossing between San Diego and Tijuana, the San Ysidro Port of Entry, is the busiest international land border crossing in the world outside of Asia (fourth-busiest overall). The city`s primary airport.', 'https://en.wikipedia.org/wiki/San_Diego', 32.71453857421875000, -117.18317413330078000, 'http://shallow.codes/images_CR12/loc18_san_diego.jpg'),
(19, 'Jackson Hole', 1502.30, 'Jackson Hole (originally called Jackson`s Hole by mountain men) is a valley between the Gros Ventre and Teton mountain ranges in..', 'Named by French trappers, “grand tetons” was the name given to the mountain range on which Jackson Hole lies. Jackson Hole`s current population is 10,553 as recorded during the 2019 census. Jackson Hole has one of the largest populations of single men aged 18 to 24 at 20%. This proportion reflects the reason for the nickname “lonely cowboy town”. The term \"hole\" was used by early trappers, or mountain men, as a term for a large mountain valley. These low-lying valleys, surrounded by mountains and containing rivers and streams, are good habitat for beavers, American bison, Elk, Moose.', 'https://en.wikipedia.org/wiki/Jackson_Hole', 43.49007415771484400, -110.75959014892578000, 'http://shallow.codes/images_CR12/loc19_jackson_hole.jpg'),
(20, 'Boston', 1578.20, 'Boston is one of the oldest municipalities in the United States, founded on the Shawmut Peninsula in 1630 by Puritan settlers..', 'Today, Boston is a thriving center of scientific research. The Boston area`s many colleges and universities make it a world leader in higher education,[22] including law, medicine, engineering and business, and the city is considered to be a global pioneer in innovation and entrepreneurship, with nearly 5,000 startups.[23][24][25] Boston`s economic base also includes finance,[26] professional and business services, biotechnology, information technology and government activities.[27] Households in the city claim the highest average rate of philanthropy in the United States;[28] businesses.', 'https://en.wikipedia.org/wiki/Boston', 42.36151504516601600, -71.05127716064453000, 'http://shallow.codes/images_CR12/loc20_boston.jpg'),
(21, 'Big Sur', 1921.10, 'Big Sur is a rugged and mountainous section of the Central Coast of California between Carmel Highlands and San Simeon, where..', 'The region is often confused with an unincorporated village, a collection of small roadside businesses and homes, also known as Big Sur.[8]:2 The larger region known as Big Sur does not have specific boundaries, but is generally considered to include the 71-mile (114 km) segment of California State Route 1 between Malpaso Creek near Carmel Highlands[9] in the north and San Carpóforo Creek near San Simeon in the south,[10] as well as the entire Santa Lucia range between these creeks.[8] The interior region is mostly uninhabited, while the coast remains relatively isolated and sparsely.', 'https://en.wikipedia.org/wiki/Big_Sur', 36.27479171752930000, -121.80899047851562000, 'http://shallow.codes/images_CR12/loc21_big_sur.jpg'),
(22, 'Chicago', 2205.10, 'Located on the shores of freshwater Lake Michigan, Chicago was incorporated as a city in 1837 near a portage between the Great..', 'Chicago is an international hub for finance, culture, commerce, industry, education, technology, telecommunications, and transportation. It is the site of the creation of the first standardized futures contracts, issued by the Chicago Board of Trade, which today is part of the largest and most diverse derivatives market in the world, generating 20% of all volume in commodities and financial futures alone.[14] O`Hare International Airport is routinely ranked among the world`s top six busiest airports according to tracked data by the Airports Council International.[15] The region also.', 'https://en.wikipedia.org/wiki/Chicago', 41.91974258422851600, -87.62312316894531000, 'http://shallow.codes/images_CR12/loc22_chicago.jpg'),
(23, 'Aspen', 2671.65, 'The City of Aspen is the Home Rule Municipality that is the county seat and the most populous municipality of Pitkin County Colo..', 'Founded as a mining camp during the Colorado Silver Boom and later named Aspen for the abundance of aspen trees in the area, the city boomed during the 1880s, its first decade. The boom ended when the Panic of 1893 led to a collapse of the silver market. For the next half-century, known as \"the quiet years\", the population steadily declined, reaching a nadir of fewer than 1000 by 1930. Aspen`s fortunes recovered in the mid-20th century when neighboring Aspen Mountain was developed into a ski resort, and industrialist Walter Paepcke bought many properties in the city in the 1950s.', 'https://en.wikipedia.org/wiki/Aspen,_Colorado', 39.22379302978515600, -106.80613708496094000, 'http://shallow.codes/images_CR12/loc23_aspen.jpg'),
(24, 'Seattle', 2646.30, 'Seattle is situated on an isthmus between Puget Sound (an inlet of the Pacific Ocean) and Lake Washington. It is the northern..', 'The Seattle area was inhabited by Native Americans for at least 4,000 years before the first permanent European settlers.[14] Arthur A. Denny and his group of travelers, subsequently known as the Denny Party, arrived from Illinois via Portland, Oregon, on the schooner Exact at Alki Point on November 13, 1851.[15] The settlement was moved to the eastern shore of Elliott Bay and named \"Seattle\" in 1852, in honor of Chief Si`ahl of the local Duwamish and Suquamish tribes. Today, Seattle has high populations of Native, Scandinavian, Asian American and African American people, as well as a.', 'https://en.wikipedia.org/wiki/Seattle', 47.60831451416015600, -122.34619140625000000, 'http://shallow.codes/images_CR12/loc24_seattle.jpg'),
(25, 'Miami', 2875.75, 'Miami is a major center and leader in finance, commerce, culture, arts, and international trade.[15][16] The metro area is by..', 'Greater Downtown Miami has one of the largest concentrations of international banks in the United States, and is home to many large national and international companies.[22] The Health District, home to Jackson Memorial Hospital and the Leonard M. Miller School of Medicine at the University of Miami among others, is a major center for hospitals, clinics, and the biotechnology and medical research industries. PortMiami is the busiest cruise port in the world in both passenger traffic and cruise lines, and refers to itself as the \"Cruise Capital of the World\".[23] Miami is also a major.', 'https://en.wikipedia.org/wiki/Miami', 25.76229476928711000, -80.19306945800781000, 'http://shallow.codes/images_CR12/loc25_miami.jpg'),
(26, 'Sedona', 2578.40, 'Sedona`s main attraction is its array of red sandstone formations. The formations appear to glow in brilliant orange and red..', 'The first Anglo settler, John J. Thompson, moved to Oak Creek Canyon in 1876, an area well known for its peach and apple orchards. The early settlers were farmers and ranchers. In 1902, when the Sedona post office was established, there were 55 residents. In the mid-1950s, the first telephone directory listed 155 names. Some parts of the Sedona area were not electrified until the 1960s. Sedona began to develop as a tourist destination, vacation-home and retirement center in the 1950s. Most of the development seen today was constructed in the 1980s and 1990s. As of 2007, there are no.', 'https://en.wikipedia.org/wiki/Sedona,_Arizona', 34.87150192260742000, -111.76634216308594000, 'http://shallow.codes/images_CR12/loc26_sedona.jpg'),
(27, 'Las Vegas', 2652.60, 'The city bills itself as The Entertainment Capital of the World, and is famous for its mega casino-hotels and associated major..', 'Las Vegas was settled in 1905 and officially incorporated in 1911. At the close of the 20th century, it was the most populated American city founded within that century (a similar distinction was earned by Chicago in the 19th century). Population growth has accelerated since the 1960s, and between 1990 and 2000 the population nearly doubled, increasing by 85.2%. Rapid growth has continued into the 21st century, and according to estimates from the U.S. Census Bureau, the city had 651,319 residents in 2019,[14] with a metropolitan population of 2,227,053. As with most major metropolitan.', 'https://en.wikipedia.org/wiki/Las_Vegas', 36.11381530761719000, -115.17905426025390000, 'http://shallow.codes/images_CR12/loc27_las_vegas.jpg'),
(28, 'Charleston, SC', 2609.85, 'Charleston is the largest city in the U.S. state of South Carolina, the county seat of Charleston County,[7] and the principal..', 'Charleston was founded in 1670 as Charles Town, honoring King Charles II, at Albemarle Point on the west bank of the Ashley River (now Charles Towne Landing) but relocated in 1680 to its present site, which became the fifth-largest city in North America within ten years. It remained unincorporated throughout the colonial period; its government was handled directly by a colonial legislature and a governor sent by Parliament. Election districts were organized according to Anglican parishes, and some social services were managed by Anglican wardens and vestries. Charleston adopted its.', 'https://en.wikipedia.org/wiki/Charleston,_South_Carolina', 32.79083251953125000, -79.89347839355469000, 'http://shallow.codes/images_CR12/loc28_charleston_SC.jpg'),
(29, 'Steamboat Springs', 2281.30, 'The city is an internationally known winter ski resort destination. The Steamboat Springs tourism industry is highlighted by the..', 'The area surrounding Steamboat Springs was originally inhabited by the Yampatika band of the Ute Tribe Utes, who hunted in the valley during the summer. Trappers began to move through the area during the first decades of the 19th century. James Harvey Crawford, the founder of Steamboat Springs, first arrived in the spring of 1874. The Crawford family moved there in 1876, and for the first five years were the sole permanent Anglo-Saxon residents of the town. The native Utes were forcibly removed from the area to a reservation in Utah by the U.S. Army starting in 1879. Milestones in the.', 'https://en.wikipedia.org/wiki/Steamboat_Springs,_Colorado', 40.51170349121094000, -106.83311462402344000, 'http://shallow.codes/images_CR12/loc29_steamboat_springs.jpg'),
(30, 'Key West', 1310.10, 'The Island of Key West is about 4 miles (6 kilometers) long and 1 mile (2 km) wide, with a total land area of 4.2 square miles..', 'Key West is the southernmost city in the contiguous United States and the westernmost island connected by highway in the Florida Keys. Duval Street, its main street, is 1.1 miles (1.8 km) in length in its 14-block-long crossing from the Gulf of Mexico to the Straits of Florida and the Atlantic Ocean. Key West is the southern terminus of U.S. Route 1, State Road A1A, the East Coast Greenway and, before 1935, the Florida East Coast Railway. Key West is a port of call for many passenger cruise ships.[12] The Key West International Airport provides airline service. Naval Air Station Key.', 'https://en.wikipedia.org/wiki/Key_West', 24.55519294738769500, -81.78140258789062000, 'http://shallow.codes/images_CR12/loc30_key_west.jpg'),
(31, 'Telluride', 1820.50, 'Telluride is the county seat and most populous town of San Miguel County in the southwestern portion of the U.S. state of Color..', 'Telluride sits in a box canyon. Steep forested mountains and cliffs surround it, with Bridal Veil Falls situated at the canyon`s head. Numerous weathered ruins of old mining operations dot the hillsides. A free gondola connects the town with its companion town, Mountain Village, Colorado, at the base of the ski area. Telluride and the surrounding area have featured prominently in popular culture, and it is the subject of several popular songs. It is especially known for its ski resort and slopes during the winter, as well as an extensive festival schedule during the summer. The Tellu.', 'https://en.wikipedia.org/wiki/Telluride,_Colorado', 37.93675231933594000, -107.81221008300781000, 'http://shallow.codes/images_CR12/loc31_telluride.jpg'),
(32, 'Monterey', 1974.90, 'Monterey (Spanish: Monterrey; Ohlone: Aacistak[11]) is a city located in Monterey County on the southern edge of Monterey Bay on..', 'During this period, Monterey hosted California`s first theater, public building, public library, publicly-funded school, printing-press, and newspaper. It was originally the only port of entry for all taxable goods in California. In 1846, during the Mexican–American War of 1846–1848, the United States flag was raised over the Customs House. After Mexico ceded California to the U.S. at the end of the war, Monterey hosted California`s first constitutional convention in 1849. The city occupies a land area of 8.466 sq mi (21.93 km2) and the city hall is at 26 feet (8 m) above sea level.', 'https://en.wikipedia.org/wiki/Monterey,_California', 36.64208984375000000, -121.90627288818360000, 'http://shallow.codes/images_CR12/loc32_monterey.jpg'),
(33, 'Outer Banks', 2407.10, 'The Outer Banks (frequently abbreviated OBX) are a 200-mile (320 km) string of barrier islands and spits off the coast of North..', 'The Outer Banks were sites of early settlement in the United States and remain important economic and cultural sites. Most notably the English Roanoke Colony vanished from Roanoke Island in 1587 and was the first location where an English person was born in the Americas, Virginia Dare was born.[2] The hundreds of shipwrecks along the Outer Banks have given the surrounding seas the nickname Graveyard of the Atlantic. The Outer Banks were also home to the Wright brothers` first flight in a controlled, powered, heavier-than-air vehicle on December 17, 1903, at Kill Devil Hills.[3] During.', 'https://en.wikipedia.org/wiki/Outer_Banks', 35.57107925415039000, -75.46468353271484000, 'http://shallow.codes/images_CR12/loc33_outer_banks.jpg'),
(34, 'Denver', 1524.70, 'Denver (/ˈdɛnvər/), officially the City and County of Denver, is the capital and most populous city of the U.S. State of Color..', 'With an estimated population of 727,211 in 2019, Denver is the 19th-most populous city in the United States, the fifth-most populous state capital, and the most populous city located in the Mountain states.[17] The metropolitan area surrounding Denver represents a majority of the population and economic activity in the Front Range region, the area where an estimated 85% of Colorado`s population lives. The Denver downtown district is immediately east of the confluence of Cherry Creek and the South Platte River, approximately 12 mi (19 km) east of the foothills of the Rocky Mountains.', 'https://en.wikipedia.org/wiki/Denver', 39.77845764160156000, -104.95461273193360000, 'http://shallow.codes/images_CR12/loc34_denver.jpg'),
(35, 'Hilton Head', 2453.80, 'Hilton Head Island, sometimes referred to as simply Hilton Head, is a Lowcountry resort town and barrier island in Beaufort Coun..', 'The island has a rich history that started with seasonal occupation by Native Americans thousands of years ago and continued with European exploration and the Sea Island Cotton trade. It became an important base of operations for the Union blockade of the Southern ports during the Civil War. Once the island fell to Union troops, hundreds of ex-slaves flocked to Hilton Head, which is still home to many of whom are descendants of freed slaves known as the Gullah (or Geechee) who have managed to hold on to much of their ethnic and cultural identity. The Town of Hilton Head Island incorp.', 'https://en.wikipedia.org/wiki/Hilton_Head_Island,_South_Carolina', 32.26078414916992000, -80.74359130859375000, 'http://shallow.codes/images_CR12/loc35_hilton_head.jpg'),
(36, 'Savannah', 2876.30, 'A savanna or savannah is a mixed woodland-grassland ecosystem characterised by the trees being sufficiently widely spaced that..', 'Savannas maintain an open canopy despite a high tree density.[4] It is often believed that savannas feature widely spaced, scattered trees. However, in many savannas, tree densities are higher and trees are more regularly spaced than in forests.[5][6][7][8] The South American savanna types cerrado sensu stricto and cerrado dense typically have densities of trees similar to or higher than that found in South American tropical forests,[5][7][8] with savanna ranging from 800–3300 trees per hectare (trees/ha) and adjacent forests with 800–2000 trees/ha. Similarly Guinean savanna has 129.', 'https://en.wikipedia.org/wiki/Savanna', 32.07950210571289000, -81.09454345703125000, 'http://shallow.codes/images_CR12/loc36_savannah.jpg'),
(37, 'Portland, OR', 1720.30, 'As of 2019, Portland had an estimated population of 654,741,[8] making it the 26th most populated city in the United States, the..', 'Named after Portland, Maine,[10] the Oregon settlement began to be populated in the 1830s near the end of the Oregon Trail. Its water access provided convenient transportation of goods, and the timber industry was a major force in the city`s early economy. At the turn of the 20th century, the city had a reputation as one of the most dangerous port cities in the world, a hub for organized crime and racketeering. After the city`s economy experienced an industrial boom during World War II, its hard-edged reputation began to dissipate. Beginning in the 1960s,[11] Portland became noted for.', 'https://en.wikipedia.org/wiki/Portland,_Oregon', 45.50799179077148400, -122.67493438720703000, 'http://shallow.codes/images_CR12/loc37_portland_OR.jpg'),
(38, 'Adirondacks', 1895.99, 'The word Adirondack is thought to come from the Mohawk word `ha-de-ron-dah` meaning `eaters of trees.` The earliest written use..', 'Humans have lived in the region of the Adirondack Mountains since the Paleo-Indian period (15,000 to 7,000 BC), shortly after the last ice age. The first group to move into the area came south from the St. Lawrence River Valley and settled along the shores of the Champlain Sea around 13,000 BC.[4] These Archaic period people, known as the Laurentian culture, were semi-nomadic hunter-gatherers. Evidence for their presence in the Adirondacks includes a projectile point of red-brown chert found in 2007 at the edge of Tupper Lake. Over the next 11,000 or so years, the region`s climate slow.', 'https://en.wikipedia.org/wiki/Adirondack_Mountains', 44.21065139770508000, -73.88658905029297000, 'http://shallow.codes/images_CR12/loc38_adirondacks.jpg'),
(39, 'Santa Fe', 1795.20, 'Santa Fe County (Spanish: Condado de Santa Fe; meaning Holy faith in Spanish) is located in the U.S. state of New Mexico. As of..', 'According to the U.S. Census Bureau, the county has a total area of 1,911 square miles (4,950 km2), of which 1,909 square miles (4,940 km2) is land and 1.5 square miles (3.9 km2) (0.08%) is water.[3] It is the fifth-smallest county in New Mexico by area. The highest point in the county is the summit of Santa Fe Baldy at 3,847 meters (12,621 ft). It is drained by the Rio Grande and several of its small tributaries. As of the 2010 census, the population was 144,170,[1] making it New Mexico`s third-most populous county, after Bernalillo County and Doña Ana County. Its county seat is Santa.', 'https://en.wikipedia.org/wiki/Santa_Fe_County,_New_Mexico', 36.02907180786133000, -106.07273101806640000, 'http://shallow.codes/images_CR12/loc39_santa_fe.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `locations`
--
ALTER TABLE `locations`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `locations`
--
ALTER TABLE `locations`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
